answer1 = int(input("Write a whole number less than 9\n>"))
print(answer1 < 9)
answer2 = int(input("Write a whole number greater than 14\n>"))
print(answer2 > 14)
answer3 = int(input("Write a whole number that is greater than 8 + 4\n>"))
print(answer3 > 8 + 4)
answer4 = int(input("Write a whole number that is less than 6 * 2\n>"))
print(answer4 < 6 * 2)
answer5 = int(input("Write a whole number that is less than 14 / 3\n>"))
print(answer5 < 14 / 3)