
from adafruit_circuitplayground import cp
import time
while True:
    import random
    diceroll = random.randint(1, 11)
    if cp.button.a:
        if diceroll == 1:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 0)
            cp.pixels[3] = (0, 0, 0)
            cp.pixels[4] = (0, 0, 0)
            cp.pixels[5] = (0, 0, 0)
            cp.pixels[6] = (0, 0, 0)
            cp.pixels[7] = (0, 0, 0)
            cp.pixels[8] = (0, 0, 0)
            cp.pixels[9] = (0, 0, 0)
            cp.pixels[1] = (0, 0, 0)
        elif diceroll == 2:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 0)
            cp.pixels[3] = (0, 0, 0)
            cp.pixels[4] = (0, 0, 0)
            cp.pixels[5] = (0, 0, 0)
            cp.pixels[6] = (0, 0, 0)
            cp.pixels[7] = (0, 0, 0)
            cp.pixels[8] = (0, 0, 0)
            cp.pixels[9] = (0, 0, 0)
            cp.pixels[1] = (0, 0, 1)
        elif diceroll == 3:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 1)
            cp.pixels[3] = (0, 0, 0)
            cp.pixels[4] = (0, 0, 0)
            cp.pixels[5] = (0, 0, 0)
            cp.pixels[6] = (0, 0, 0)
            cp.pixels[7] = (0, 0, 0)
            cp.pixels[8] = (0, 0, 0)
            cp.pixels[9] = (0, 0, 0)
            cp.pixels[1] = (0, 0, 1)
        elif diceroll == 4:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 1)
            cp.pixels[3] = (0, 0, 1)
            cp.pixels[4] = (0, 0, 0)
            cp.pixels[5] = (0, 0, 0)
            cp.pixels[6] = (0, 0, 0)
            cp.pixels[7] = (0, 0, 0)
            cp.pixels[8] = (0, 0, 0)
            cp.pixels[9] = (0, 0, 0)
            cp.pixels[1] = (0, 0, 1)
        elif diceroll == 5:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 1)
            cp.pixels[3] = (0, 0, 1)
            cp.pixels[4] = (0, 0, 1)
            cp.pixels[5] = (0, 0, 0)
            cp.pixels[6] = (0, 0, 0)
            cp.pixels[7] = (0, 0, 0)
            cp.pixels[8] = (0, 0, 0)
            cp.pixels[9] = (0, 0, 0)
            cp.pixels[1] = (0, 0, 1)
        elif diceroll == 6:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 1)
            cp.pixels[3] = (0, 0, 1)
            cp.pixels[4] = (0, 0, 1)
            cp.pixels[5] = (0, 0, 1)
            cp.pixels[6] = (0, 0, 0)
            cp.pixels[7] = (0, 0, 0)
            cp.pixels[8] = (0, 0, 0)
            cp.pixels[9] = (0, 0, 0)
            cp.pixels[1] = (0, 0, 1)
        elif diceroll == 7:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 1)
            cp.pixels[3] = (0, 0, 1)
            cp.pixels[4] = (0, 0, 1)
            cp.pixels[5] = (0, 0, 1)
            cp.pixels[6] = (0, 0, 1)
            cp.pixels[7] = (0, 0, 0)
            cp.pixels[8] = (0, 0, 0)
            cp.pixels[9] = (0, 0, 0)
            cp.pixels[1] = (0, 0, 1)
        elif diceroll == 8:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 1)
            cp.pixels[3] = (0, 0, 1)
            cp.pixels[4] = (0, 0, 1)
            cp.pixels[5] = (0, 0, 1)
            cp.pixels[6] = (0, 0, 1)
            cp.pixels[7] = (0, 0, 1)
            cp.pixels[8] = (0, 0, 0)
            cp.pixels[9] = (0, 0, 0)
            cp.pixels[1] = (0, 0, 1)
        elif diceroll == 9:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 1)
            cp.pixels[3] = (0, 0, 1)
            cp.pixels[4] = (0, 0, 1)
            cp.pixels[5] = (0, 0, 1)
            cp.pixels[6] = (0, 0, 1)
            cp.pixels[7] = (0, 0, 1)
            cp.pixels[8] = (0, 0, 1)
            cp.pixels[9] = (0, 0, 0)
            cp.pixels[1] = (0, 0, 1)
        elif diceroll == 10:
            cp.pixels[0] = (0, 0, 1)
            cp.pixels[2] = (0, 0, 1)
            cp.pixels[3] = (0, 0, 1)
            cp.pixels[4] = (0, 0, 1)
            cp.pixels[5] = (0, 0, 1)
            cp.pixels[6] = (0, 0, 1)
            cp.pixels[7] = (0, 0, 1)
            cp.pixels[8] = (0, 0, 1)
            cp.pixels[9] = (0, 0, 1)
            cp.pixels[1] = (0, 0, 1)
    if cp.button.b:
        cp.pixels.fill((0, 0, 0))
